{{- if .Values.controlPlane.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "parallax.fullname" . }}-control-plane
  labels:
    {{- include "parallax.controlPlane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controlPlane.service.type }}
  ports:
    - port: {{ .Values.controlPlane.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.controlPlane.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "parallax.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
{{- end }}